name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform validate
